### PR TITLE
chore: temp release node.js and python SDK

### PR DESCRIPTION
**Pull request by Peefy**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [x] N
- [ ] Y 

ci: temp release for kcl python lib 0.8.5 and kcl node.js lib 0.8.6-rc.1

python release page: https://pypi.org/project/kcl-lib/
node.js release page: https://www.npmjs.com/search?q=kcl-lib

### CODE REVIEW

**Review by jianzs — APPROVED** [review]
The Node.js SDK works on Linux x86_64. However, I noticed a small error in the README file - it's missing the 'new' keyword for the argument when calling execProgram. The correct syntax should be `new ExecProgramArgs(['__test__/test_data/schema.k'])`.

**Comment by Peefy** [comment]
@jianzs Thank you! I will open another PR to fix this. In javascipt, it's ok and you have used typesciprt, right?

**Comment by jianzs** [comment]
> @jianzs Thank you! I will open another PR to fix this. In javascipt, it's ok and you have used typesciprt, right?

Yes, I've tested using TypeScript.

**Comment by Peefy** [comment]
@jianzs PTAL. https://github.com/kcl-lang/lib/pull/63

**Pull request merged**
